server:
  port: 8100

spring:
  application:
    name: artemis
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:15432/Artemis?createDatabaseIfNotExist=true&useSSL=false
    username: postgres 
    password: postgres 
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update 
    properties:
      dialect: org.hibernate.dialect.PostgreSQLDialect
  jackson:
    default-property-inclusion: NON_NULL
    serialization:
      fail-on-empty-beans: false
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: 123456

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9900/eureka

